#!/usr/bin/awk -f
#
# Used to generate armordb.clj:
# $ ./armordb.awk darksouls-armor-stats-10.csv
#

BEGIN {
        FS = ","
        print ";;; generated by armordb.awk, do not modify\n"

        print "(ns darktools.armordb"
        print "  (:refer-clojure :exclude [==])"
        print "  (:use clojure.core.logic))\n"

        printf "(defrel armor name "
        printf "^:index position ^:index poise ^:index weight "
        printf "physical magic fire lightning "
        printf "bleed poison curse)\n"
}

NR == 1 { next } #skip header

{
        printf "(fact armor "
        for (i = 2; i < NF-2; i++) printf $i " "
        printf $i ")\n"
}

END {
        print "\n(defrel position symbolic numeric)"
        print "(fact position :head 1)"
        print "(fact position :torso 2)"
        print "(fact position :arms 3)"
        print "(fact position :legs 4)\n"

        print ";;; eof"
}

# eof
